<a href="https://colab.research.google.com/github/Mariamacedo-prog/AdoCao-AdoCats/blob/main/estudoPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

print(f'O resultado de {n1} dividivo por {n2} é {n1/n2}');

In [ ]:
import math

math.sqrt(81)

In [ ]:
tempo = 8
velocidade = 90

In [ ]:
distancia = tempo * velocidade
print(distancia)

720


In [ ]:
litros = distancia / 12
print(litros)

60.0


In [ ]:
n3 = int(input('digite seu numero: '))
n4 = int(input('digite seu numero: '))

digite seu numero: 2
digite seu numero: 4


In [ ]:
adicao = n3+n4
subtraçao  = n3-n4
divisao  = n3/n4
multiplicacao  = n3*n4

print("adição: ", adicao)
print("subtraçao: ", subtraçao)
print("divisao: ", round(divisao, 2))
print("multiplicacao: ", multiplicacao)

adição:  6
subtraçao:  -2
divisao:  0.5
multiplicacao:  8


In [ ]:
tempo = float(input('digite seu tempo: '))
velocidade = float(input('digite sua velocidade: '))

digite seu tempo: 2
digite sua velocidade: 80


In [ ]:
distancia = tempo * velocidade
litros = distancia / 12

print("Seu tempo médio foi de: ", tempo)
print("Sua velocidade foi de: ", velocidade)
print("Distacia média: ", distancia)
print("Litros gastos ", round(litros, 1))

Seu tempo médio foi de:  2.0
Sua velocidade foi de:  80.0
Distacia média:  160.0
Litros gastos  13.3


In [ ]:
5!=3

True

In [ ]:
if 5 > 3:
  print("5 é maior")
else:
  print("5 não é maior")

5 é maior


In [ ]:
n = int(input('digite o número'))

if n == 4: 
  print('n é igual a 4')
else:
  if n == 3: 
    print('n igual a 3')
  else:
   print('n não é 3 nem 4')

digite o número10
n não é 3 nem 4


In [ ]:
idade = int(input('digite usa idade: '))


if (idade <= 12 and idade >= 0): 
  print('Criança')
else:
  if (idade <= 18 and idade > 12): 
    print('Adolescente')
  else:
    if (idade > 18): 
     print('Adulto')
    else:
      print('Idade invalida')

digite usa idade: -18
Idade invalida


In [ ]:
M1 = float(input('digite a média do M1: '))
M2 = float(input('digite a média do M1: '))
M3 = float(input('digite a média do M1: '))

soma = M1 + M2 + M3
media = soma / 3
media_arr = round(media, 1)

print(media_arr)

digite a média do M1: 6.
digite a média do M1: 6
digite a média do M1: 6
6.0


In [ ]:
if (media_arr >= 0.0 and media_arr <= 4.0):
  print('Reprovado')
else:
  if (media_arr <= 6.0):
    print('o aluno pegou exame')
    exame = float(input('digite a nota do exame: '))
    exame_arr = round(exame, 1)
    if ( exame_arr >= 6.0):
      print('está aprovado')
    else:
      print('Reprovado')
  else:
    if (media_arr >= 6.0):
      print('está aprovado')

o aluno pegou exame
digite a nota do exame: 5
Reprovado


In [ ]:
for numero in range(1 , 6):
  print(numero)

1
2
3
4
5


In [ ]:
for numero in range(5, 0, -1):
  print(numero)

5
4
3
2
1


In [ ]:
soma =0

for numero in range(1,6):
  soma = soma + numero
print(soma)

15


In [ ]:
palavra = 'sorvete'

for letra in palavra:
  print(letra)

s
o
r
v
e
t
e


In [ ]:
numero = 1

while numero < 6:
  print(numero)
  numero += 1
print(numero)

1
2
3
4
5
6


In [ ]:
numero = 5

while numero > 0:
  print(numero)
  numero -= 1
  

5
4
3
2
1


In [ ]:
soma = 0
numero = 1
while numero < 6:
  soma += numero
  numero +=1
  print(soma)


1
3
6
10
15


In [ ]:
numero = -1

while numero < 1 or numero > 10:
  numero = int(input('digite um numero de 1 até 10: 1'))

digite um numero de 1 até 10: -1
digite um numero de 1 até 10: -3
digite um numero de 1 até 10: 0
digite um numero de 1 até 10: 21
digite um numero de 1 até 10: 3


In [ ]:
soma = nota = media = 0

for _ in range(1, 6):
  nota = float(input('digite a nota: '))
  soma += nota
  print(soma)

media = soma / 5
print('sua média é de: ', media)

numero = 0

while numero < 10:
  numero +=1
  print(numero * 3)


digite a nota: 5
5.0
digite a nota: 6
11.0
digite a nota: 7
18.0
digite a nota: 8
26.0
digite a nota: 5
31.0
sua média é de:  6.2
3
6
9
12
15
18
21
24
27
30


In [ ]:
l1 = ['gato', 'cachorro', 'homem']

l1.append('gorila')


print(l1)

l1.remove('gorila')

print(l1)

['gato', 'cachorro', 'homem', 'gorila']
['gato', 'cachorro', 'homem']


In [ ]:
conj = ('gato', 'cachorro', 'homem gato', 'cachorro', 'homem')

print(set(conj))

{'gato', 'homem', 'homem gato', 'cachorro'}


In [ ]:
c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7}

c3 = c1.intersection(c2)

print(c3)

c2.difference(c1)
c1.difference(c2)

{3, 4, 5}


{1, 2}

In [ ]:
import numpy as np




In [ ]:
matriz = np.array([[1,2,3], [4,5,6]])

matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matriz.shape

matriz[0]

matriz[1]



array([4, 5, 6])

In [22]:
matriz[1][2]


6

In [24]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [32]:
lista = []

numero = 0
soma = 0

while numero < 5: 
   n = int(input('digite um numero inteiro: '))

   lista.append(n)
   numero += 1
   print(lista)


for i in lista:
  soma = soma + i
print(soma)

digite um numero inteiro: 123
[123]
digite um numero inteiro: 666
[123, 666]
digite um numero inteiro: 212
[123, 666, 212]
digite um numero inteiro: 3234
[123, 666, 212, 3234]
digite um numero inteiro: 544
[123, 666, 212, 3234, 544]
4779


In [39]:
num = 0

dic = {}

while num < 3:
  nome = (input('digite o nome: '))
  nota = float(input('digite a nota: '))

  dic[nome] = nota
  num = num + 1
  print(f'Aluno(a) {nome} teve nota {nota}')

print(dic)



digite o nome: Maria
digite a nota: 6.5
Aluno(a) Maria teve nota 6.5
digite o nome: João 
digite a nota: 7.5
Aluno(a) João  teve nota 7.5
digite o nome: Steffany
digite a nota: 3.5
Aluno(a) Steffany teve nota 3.5
{'Maria': 6.5, 'João ': 7.5, 'Steffany': 3.5}


In [42]:
notas = dic.values()

soma = 0 

for i in notas:
  soma= soma + i
  print(soma)


6.5
14.0
17.5


In [48]:
media = soma / 3

print(f' A média da sala é {round(media, 1)}')

 A média da sala é 5.8


In [51]:
matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

somaEle = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    elemento = matriz[i][j]

    somaEle += elemento
print(somaEle)


17


In [52]:
def mensagem():
  print('função criada')

In [53]:
mensagem()

função criada


In [54]:
def mensagem(texto):
  print(texto)

In [55]:
mensagem('primeiro texto')
mensagem('segundo texto')
mensagem('terceiro texto')


primeiro texto
segundo texto
terceiro texto


In [60]:
def energiaCalGravitaciona(m, h, g=10):
  '''aqui fica o comentário do help'''
  
  e = g * m * h
  return e

In [57]:
energiaCalGravitaciona(30, 12)

3600

In [61]:
help(energiaCalGravitaciona)

Help on function energiaCalGravitaciona in module __main__:

energiaCalGravitaciona(m, h, g=10)
    aqui fica o comentário do help



In [139]:
def primeiraFunc():
  C = float(input('digite o Celsis: '))
  return C

In [140]:
Cel = primeiraFunc()
print(Cel)

def segundaFunc(Cel):
  F = (9 * Cel + 160) / 5
  return F

digite o Celsis: 20
20.0


In [141]:
Far = segundaFunc(Cel)
print(Far)


68.0


In [142]:
def terceiraFunc(Cel, Far):
  print(f'{Cel} Celsius são {Far} Far')

In [143]:
r = terceiraFunc(Cel, Far)
print(r)

20.0 Celsius são 68.0 Far
None


In [104]:
def viagem():
  '''12 Km por litro. Para obter o cálculo, o usuário deve fornecer o tempo gasto na viagem e a velocidade média durante ela. 
   DISTANCIA = TEMPO * VELOCIDADE.
   LITROS_USADOS = DISTANCIA / 12. O programa deve apresentar os valores da velocidade média, tempo gasto na viagem, a distância percorrida e a quantidade de litros utilizada na viagem
- Função para ler os valores (não recebe parâmetro e retorna os dois valores)
- Função para calcular a distância (recebe como parâmetro o tempo e a velocidade e retorna a distância)
- Função para calcular a quantidade de litros (recebe como parâmetro a distância e retorna os litros)
- Função para apresentar o resultado (recebe como parâmetro os valores e somente imprime o resultado)'''
  tempo = float(input('digite seu tempo: '))
  velocidade = float(input('digite sua velocidade: '))

  return tempo, velocidade


In [122]:
def distace (tempo, velocidade):
  D = tempo * velocidade
  return D

In [123]:


def litros(resultado_distancia):
  LITROS_USADOS = resultado_distancia / 12
  return LITROS_USADOS



In [124]:
def ultima(tempo, velocidade, resultado_distancia, li):
  print("Seu tempo médio foi de: ", tempo)
  print("Sua velocidade foi de: ", velocidade)
  print("Distacia média: ", resultado_distancia)
  print("Litros gastos ", round(li, 1))

In [146]:
t, v = viagem()

d = distace(t, v)

l = litros(d)

ultima(t, v, d, l)

digite seu tempo: 5
digite sua velocidade: 90
Seu tempo médio foi de:  5.0
Sua velocidade foi de:  90.0
Distacia média:  450.0
Litros gastos  37.5
